# Generated by Django 4.1.4 on 2023-09-24 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_remove_question_vote_question_downvoters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='vote',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoters',
            field=models.ManyToManyField(null=True, related_name='downvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoters',
            field=models.ManyToManyField(null=True, related_name='upvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
