# Generated by Django 4.1.4 on 2023-09-27 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_remove_answer_vote_answer_downvoters_answer_upvoters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='on_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='on_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='on_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='on_update',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
